import React from "react";
import "./globals.css";
import Header from "./components/Header";

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>NextjS with Prisma-1</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
